/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebdesignRouteImport } from './routes/webdesign'
import { Route as SocialmediaRouteImport } from './routes/socialmedia'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnWebdesignRouteImport } from './routes/en_.webdesign'
import { Route as EnSocialmediaRouteImport } from './routes/en_.socialmedia'

const WebdesignRoute = WebdesignRouteImport.update({
  id: '/webdesign',
  path: '/webdesign',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialmediaRoute = SocialmediaRouteImport.update({
  id: '/socialmedia',
  path: '/socialmedia',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnWebdesignRoute = EnWebdesignRouteImport.update({
  id: '/en_/webdesign',
  path: '/en/webdesign',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSocialmediaRoute = EnSocialmediaRouteImport.update({
  id: '/en_/socialmedia',
  path: '/en/socialmedia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/socialmedia': typeof SocialmediaRoute
  '/webdesign': typeof WebdesignRoute
  '/en/socialmedia': typeof EnSocialmediaRoute
  '/en/webdesign': typeof EnWebdesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/socialmedia': typeof SocialmediaRoute
  '/webdesign': typeof WebdesignRoute
  '/en/socialmedia': typeof EnSocialmediaRoute
  '/en/webdesign': typeof EnWebdesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/socialmedia': typeof SocialmediaRoute
  '/webdesign': typeof WebdesignRoute
  '/en_/socialmedia': typeof EnSocialmediaRoute
  '/en_/webdesign': typeof EnWebdesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/socialmedia'
    | '/webdesign'
    | '/en/socialmedia'
    | '/en/webdesign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/socialmedia'
    | '/webdesign'
    | '/en/socialmedia'
    | '/en/webdesign'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/socialmedia'
    | '/webdesign'
    | '/en_/socialmedia'
    | '/en_/webdesign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  SocialmediaRoute: typeof SocialmediaRoute
  WebdesignRoute: typeof WebdesignRoute
  EnSocialmediaRoute: typeof EnSocialmediaRoute
  EnWebdesignRoute: typeof EnWebdesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webdesign': {
      id: '/webdesign'
      path: '/webdesign'
      fullPath: '/webdesign'
      preLoaderRoute: typeof WebdesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socialmedia': {
      id: '/socialmedia'
      path: '/socialmedia'
      fullPath: '/socialmedia'
      preLoaderRoute: typeof SocialmediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en_/webdesign': {
      id: '/en_/webdesign'
      path: '/en/webdesign'
      fullPath: '/en/webdesign'
      preLoaderRoute: typeof EnWebdesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en_/socialmedia': {
      id: '/en_/socialmedia'
      path: '/en/socialmedia'
      fullPath: '/en/socialmedia'
      preLoaderRoute: typeof EnSocialmediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  SocialmediaRoute: SocialmediaRoute,
  WebdesignRoute: WebdesignRoute,
  EnSocialmediaRoute: EnSocialmediaRoute,
  EnWebdesignRoute: EnWebdesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
